# gw-isl-dts 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-isl-dts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-isl-dts
  template:
    metadata:
      labels:
        app: gw-isl-dts
    spec:
      containers:
      - name: gw-isl-dts
        image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/fuelics/demo/gw-isl-dts:0.40.1
        ports:
        - containerPort: 60000
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        env:
        - name: API_CFG
          value: ./api_cfg.yaml
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ./api-services@fuelics-alpha-11.iam.gserviceaccount.com.json
        - name: GW_CFG
          value: ./gw_cfg.yaml
        - name: PROJECT_ID
          value: fuelics-alpha-11
        - name: RUST_LOG
          value: none,gw=debug
        volumeMounts:
        - name: fdb-vol
          mountPath: /srv/gw-isl-dts/fdb
      volumes:
      - name: fdb-vol
        hostPath:
          path: /fdb
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: worker-node-1
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gw-isl-dts
spec:
  type: NodePort
  selector:
    app: gw-isl-dts
  ports:
  - name: gw-signal
    port: 60000
    targetPort: 60000
    protocol: UDP
    nodePort: 31702
  - name: gw-api
    port: 80
    targetPort: 80
    protocol: TCP
    
---

# reverse-proxy 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/fuelics/demo/reverse-proxy:2.1.1
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: certstore-vol
          mountPath: /srv/proxy/acme-certstore
      volumes:
      - name: certstore-vol
        hostPath:
          path: /srv/acme/certstore
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: worker-node-1
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-http
spec:
  type: NodePort
  selector:
    app: reverse-proxy
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-https
spec:
  type: NodePort
  selector:
    app: reverse-proxy
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30443

# api-foreground 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-foreground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-foreground
  template:
    metadata:
      labels:
        app: api-foreground
    spec:
      containers:
      - name: api-foreground
        image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/fuelics/demo/api/foreground:9.7.12
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: lead-worker
      imagePullSecrets:
      - name: regcred
---     
apiVersion: v1
kind: Service
metadata:
  name: api-foreground
spec:
  selector:
    app: api-foreground
  ports:
    - port: 80
      targetPort: 80
---

# api 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/fuelics/demo/api:0.40.1
        ports:
        - containerPort: 80
        env:
        - name: API_CFG
          value: ./api_cfg.yaml
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ./service-account.json
        - name: PROJECT_ID
          value: fuelics-alpha-11
        - name: RUST_LOG
          value: none,api=debug
      nodeSelector:
        kubernetes.io/hostname: lead-worker
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
---

# web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/fuelics/demo/web:4.7.3
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: lead-worker
      imagePullSecrets:
      - name: regcred
---     
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
---
