apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-foreground
  labels:
    app: api-foreground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-foreground
  template:
    metadata:
      labels:
        app: api-foreground
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api-foreground
          image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/fuelics/api/foreground:9.7.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-foreground
  labels:
    app: api-foreground
spec:
  selector:
    app: api-foreground
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

