apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: reverse-proxy
          image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/fuelics/reverse-proxy:2.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: certstore-vol
              mountPath: /srv/acme/certstore
      volumes:
        - name: certstore-vol
          hostPath:
            path: /srv/acme/certstore
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  selector:
    app: reverse-proxy
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP

