#!/usr/bin/env bash
# =============================================================================
# Swarmchestrate K3s Installer
# Installs K3s on a pre-provisioned node and registers it with the
# Swarmchestrate node label (labels.swarmchestrate.eu/ms_id).
#
# Roles:   master | worker
#
# Usage:
#   Standalone master (auto-generates token):
#     sudo ./install-k3s.sh \
#       --role master \
#       --node-name my-master \
#       --cluster-name my-cluster
#
#   Standalone master (bring your own token):
#     sudo ./install-k3s.sh \
#       --role master \
#       --node-name my-master \
#       --cluster-name my-cluster \
#       --token mysecrettoken
#
#   Worker (use token and IP from master output):
#     sudo ./install-k3s.sh \
#       --role worker \
#       --node-name my-worker \
#       --cluster-name my-cluster \
#       --token <token> \
#       --master-ip <master-ip>
#
# Optional flags:
#   --k3s-version   Pin a specific K3s version e.g. v1.32.3+k3s1
#   --flannel-iface Override Flannel interface e.g. tailscale0
#   --node-ip       Explicit node IP to advertise (multi-NIC or VPN setups)
#   --tls-san       Extra SAN for the API server TLS cert (repeatable)
#   --extra-labels  Comma-separated extra node labels e.g. region=eu,tier=edge
#   --dry-run       Print resolved config without installing anything
# =============================================================================
set -euo pipefail

# ── colour helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
die()     { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

# ── defaults ──────────────────────────────────────────────────────────────────
ROLE=""
NODE_NAME=""
CLUSTER_NAME=""
TOKEN=""
MASTER_IP=""
K3S_VERSION=""
FLANNEL_IFACE=""
NODE_IP=""
TLS_SANS=()
EXTRA_LABELS=""
DRY_RUN=false

INSTALL_SCRIPT_URL="https://get.k3s.io"

# ── arg parsing ───────────────────────────────────────────────────────────────
usage() {
  grep '^#' "$0" | grep -v '#!/' | sed 's/^# \{0,2\}//' | head -40
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --role)          ROLE="$2";           shift 2 ;;
    --node-name)     NODE_NAME="$2";      shift 2 ;;
    --cluster-name)  CLUSTER_NAME="$2";   shift 2 ;;
    --token)         TOKEN="$2";          shift 2 ;;
    --master-ip)     MASTER_IP="$2";      shift 2 ;;
    --k3s-version)   K3S_VERSION="$2";    shift 2 ;;
    --flannel-iface) FLANNEL_IFACE="$2";  shift 2 ;;
    --node-ip)       NODE_IP="$2";        shift 2 ;;
    --tls-san)       TLS_SANS+=("$2");    shift 2 ;;
    --extra-labels)  EXTRA_LABELS="$2";   shift 2 ;;
    --dry-run)       DRY_RUN=true;        shift ;;
    -h|--help)       usage ;;
    *) die "Unknown argument: $1" ;;
  esac
done

# ── validation ────────────────────────────────────────────────────────────────
[[ -n "$ROLE" ]]         || die "--role is required  (master | worker)"
[[ -n "$NODE_NAME" ]]    || die "--node-name is required"
[[ -n "$CLUSTER_NAME" ]] || die "--cluster-name is required"

case "$ROLE" in
  master) ;;
  worker)
    [[ -n "$MASTER_IP" ]] || die "--master-ip is required for role 'worker'"
    [[ -n "$TOKEN" ]]     || die "--token is required for role 'worker'"
    ;;
  *) die "Unknown role '$ROLE'. Use: master | worker" ;;
esac

# ── root check ────────────────────────────────────────────────────────────────
if [[ "$DRY_RUN" == false && $EUID -ne 0 ]]; then
  die "Run as root (or with sudo)"
fi

# ── token: generate if not provided (master only) ─────────────────────────────
resolve_token() {
  if [[ "$ROLE" == "master" && -z "$TOKEN" ]]; then
    if command -v openssl &>/dev/null; then
      TOKEN="$(openssl rand -hex 32)"
    else
      TOKEN="$(tr -dc 'a-f0-9' < /dev/urandom | head -c 64)"
    fi
    info "No --token provided — generated a secure token"
  fi
}

# ── build node labels ─────────────────────────────────────────────────────────
build_node_labels() {
  local labels="labels.swarmchestrate.eu/ms_id=${NODE_NAME}"
  if [[ -n "$EXTRA_LABELS" ]]; then
    IFS=',' read -ra EXTRA <<< "$EXTRA_LABELS"
    for lbl in "${EXTRA[@]}"; do
      labels+=$'\n'"node-label: ${lbl}"
    done
  fi
  echo "$labels"
}

# ── build /etc/rancher/k3s/config.yaml ───────────────────────────────────────
build_config_yaml() {
  local node_labels
  node_labels="$(build_node_labels)"

  echo "# Generated by Swarmchestrate install-k3s.sh"
  echo "# Role: ${ROLE}"
  echo ""
  echo "node-name: ${NODE_NAME}"
  echo "node-label: ${node_labels}"

  if [[ "$ROLE" == "master" ]]; then
    echo "cluster-name: ${CLUSTER_NAME}"
  fi

  if [[ "$ROLE" == "worker" ]]; then
    echo "server: https://${MASTER_IP}:6443"
    echo "token: ${TOKEN}"
  fi

  [[ -n "$FLANNEL_IFACE" ]] && echo "flannel-iface: ${FLANNEL_IFACE}"
  [[ -n "$NODE_IP" ]]       && echo "node-ip: ${NODE_IP}"
  for san in "${TLS_SANS[@]}"; do
    echo "tls-san: ${san}"
  done
}

# ── resolve installer env vars ────────────────────────────────────────────────
resolve_install_env() {
  local -n _env=$1

  [[ -n "$K3S_VERSION" ]] && _env["INSTALL_K3S_VERSION"]="$K3S_VERSION"

  case "$ROLE" in
    master)
      _env["INSTALL_K3S_EXEC"]="server"
      _env["K3S_TOKEN"]="$TOKEN"
      _env["K3S_CLUSTER_INIT"]="true"
      ;;
    worker)
      _env["INSTALL_K3S_EXEC"]="agent"
      _env["K3S_TOKEN"]="$TOKEN"
      _env["K3S_URL"]="https://${MASTER_IP}:6443"
      ;;
  esac
}

# ── cgroup check (Raspberry Pi / ARM) ─────────────────────────────────────────
check_cgroups() {
  if grep -q "Raspberry Pi\|BCM2\|BCM27" /proc/cpuinfo 2>/dev/null || \
     [[ "$(uname -m)" =~ ^arm ]]; then
    info "ARM / Raspberry Pi detected — checking cgroup parameters..."

    local cmdline_file=""
    [[ -f /boot/firmware/cmdline.txt ]] && cmdline_file="/boot/firmware/cmdline.txt"
    [[ -z "$cmdline_file" && -f /boot/cmdline.txt ]] && cmdline_file="/boot/cmdline.txt"

    if [[ -n "$cmdline_file" ]]; then
      if ! grep -q "cgroup_memory=1" "$cmdline_file"; then
        warn "cgroup_memory=1 missing from $cmdline_file"
        sed -i 's/$/ cgroup_memory=1 cgroup_enable=memory/' "$cmdline_file"
        success "Added cgroup params to $cmdline_file"
        warn "Reboot this node then re-run the script to complete installation."
        exit 0
      else
        success "cgroup params already present"
      fi
    fi
  fi
}

# ── write config ──────────────────────────────────────────────────────────────
write_k3s_config() {
  info "Writing /etc/rancher/k3s/config.yaml..."
  mkdir -p /etc/rancher/k3s
  build_config_yaml > /etc/rancher/k3s/config.yaml
  chmod 600 /etc/rancher/k3s/config.yaml
  success "/etc/rancher/k3s/config.yaml written"
}

# ── run installer ─────────────────────────────────────────────────────────────
run_installer() {
  declare -A ENV_VARS=()
  resolve_install_env ENV_VARS

  info "Downloading and running K3s installer..."

  local env_prefix=""
  for key in "${!ENV_VARS[@]}"; do
    env_prefix="${env_prefix} ${key}=${ENV_VARS[$key]}"
  done

  # shellcheck disable=SC2086
  eval "env ${env_prefix} sh -s - --config /etc/rancher/k3s/config.yaml" \
    < <(curl -sfL "$INSTALL_SCRIPT_URL")

  success "K3s installer completed"
}

# ── wait for node Ready ───────────────────────────────────────────────────────
wait_for_ready() {
  if [[ "$ROLE" == "worker" ]]; then
    info "Worker registered. Verify on master with: kubectl get nodes"
    return
  fi

  info "Waiting for node to become Ready (up to 120s)..."
  local retries=0
  until kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml \
        get node "$NODE_NAME" \
        -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null \
        | grep -q "True"; do
    if [[ $retries -ge 24 ]]; then
      warn "Not Ready after 120s — check: journalctl -u k3s -f"
      return
    fi
    sleep 5
    (( retries++ ))
  done
  success "Node '${NODE_NAME}' is Ready"
}

# ── verify labels ─────────────────────────────────────────────────────────────
verify_labels() {
  [[ "$ROLE" == "worker" ]] && return
  info "Verifying node labels..."
  kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml \
    get node "$NODE_NAME" --show-labels 2>/dev/null \
    || warn "Could not retrieve labels — check manually: kubectl get node ${NODE_NAME} --show-labels"
}

# ── final summary ─────────────────────────────────────────────────────────────
print_summary() {
  if [[ "$ROLE" == "master" ]]; then
    local master_ip
    master_ip="${NODE_IP:-$(hostname -I | awk '{print $1}')}"

    echo ""
    echo -e "${BOLD}╔══════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}║           MASTER INSTALLATION COMPLETE          ║${RESET}"
    echo -e "${BOLD}╠══════════════════════════════════════════════════╣${RESET}"
    echo -e "${BOLD}║${RESET}  Cluster   : ${CLUSTER_NAME}"
    echo -e "${BOLD}║${RESET}  Node      : ${NODE_NAME}"
    echo -e "${BOLD}║${RESET}"
    echo -e "${BOLD}║${RESET}  ${YELLOW}Use these values to join worker nodes:${RESET}"
    echo -e "${BOLD}║${RESET}"
    echo -e "${BOLD}║${RESET}  Master IP : ${GREEN}${master_ip}${RESET}"
    echo -e "${BOLD}║${RESET}  Token     : ${GREEN}${TOKEN}${RESET}"
    echo -e "${BOLD}║${RESET}"
    echo -e "${BOLD}║${RESET}  Worker join command:"
    echo -e "${BOLD}║${RESET}  ${CYAN}sudo ./install-k3s.sh \\${RESET}"
    echo -e "${BOLD}║${RESET}  ${CYAN}  --role worker \\${RESET}"
    echo -e "${BOLD}║${RESET}  ${CYAN}  --node-name <worker-name> \\${RESET}"
    echo -e "${BOLD}║${RESET}  ${CYAN}  --cluster-name ${CLUSTER_NAME} \\${RESET}"
    echo -e "${BOLD}║${RESET}  ${CYAN}  --token ${TOKEN} \\${RESET}"
    echo -e "${BOLD}║${RESET}  ${CYAN}  --master-ip ${master_ip}${RESET}"
    echo -e "${BOLD}║${RESET}"
    echo -e "${BOLD}║${RESET}  Kubeconfig: /etc/rancher/k3s/k3s.yaml"
    echo -e "${BOLD}║${RESET}  Copy for current user:"
    echo -e "${BOLD}║${RESET}  ${CYAN}mkdir -p ~/.kube${RESET}"
    echo -e "${BOLD}║${RESET}  ${CYAN}sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config${RESET}"
    echo -e "${BOLD}║${RESET}  ${CYAN}sudo chown \$(id -u):\$(id -g) ~/.kube/config${RESET}"
    echo -e "${BOLD}╚══════════════════════════════════════════════════╝${RESET}"
    echo ""
  else
    echo ""
    echo -e "${BOLD}╔══════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}║           WORKER INSTALLATION COMPLETE          ║${RESET}"
    echo -e "${BOLD}╠══════════════════════════════════════════════════╣${RESET}"
    echo -e "${BOLD}║${RESET}  Cluster   : ${CLUSTER_NAME}"
    echo -e "${BOLD}║${RESET}  Node      : ${NODE_NAME}"
    echo -e "${BOLD}║${RESET}  Master IP : ${MASTER_IP}"
    echo -e "${BOLD}║${RESET}"
    echo -e "${BOLD}║${RESET}  Verify on master:"
    echo -e "${BOLD}║${RESET}  ${CYAN}kubectl get nodes${RESET}"
    echo -e "${BOLD}╚══════════════════════════════════════════════════╝${RESET}"
    echo ""
  fi
}

# ── dry run summary ───────────────────────────────────────────────────────────
dry_run_summary() {
  declare -A ENV_VARS=()
  resolve_install_env ENV_VARS

  echo ""
  echo -e "${BOLD}═══════════════ DRY RUN SUMMARY ═══════════════${RESET}"
  echo -e "  Role          : ${YELLOW}${ROLE}${RESET}"
  echo -e "  Node name     : ${NODE_NAME}"
  echo -e "  Cluster name  : ${CLUSTER_NAME}"
  echo -e "  Master IP     : ${MASTER_IP:-n/a}"
  echo -e "  Flannel iface : ${FLANNEL_IFACE:-default}"
  echo -e "  Node IP       : ${NODE_IP:-auto-detect}"
  echo -e "  TLS SANs      : ${TLS_SANS[*]:-none}"
  echo -e "  Extra labels  : ${EXTRA_LABELS:-none}"
  echo -e "  K3s version   : ${K3S_VERSION:-latest stable}"
  echo -e "  Token         : ${TOKEN:+***}${TOKEN:-auto-generate}"
  echo ""
  echo -e "${BOLD}Installer env vars:${RESET}"
  for key in "${!ENV_VARS[@]}"; do
    if [[ "$key" == *TOKEN* ]]; then
      echo -e "  ${key}=***"
    else
      echo -e "  ${key}=${ENV_VARS[$key]}"
    fi
  done
  echo ""
  echo -e "${BOLD}/etc/rancher/k3s/config.yaml:${RESET}"
  echo "---"
  build_config_yaml
  echo "---"
}

# ── main ──────────────────────────────────────────────────────────────────────
main() {
  echo ""
  echo -e "${BOLD}Swarmchestrate K3s Installer${RESET}"
  echo -e "Role: ${YELLOW}${ROLE}${RESET} | Node: ${NODE_NAME} | Cluster: ${CLUSTER_NAME}"
  echo ""

  resolve_token

  if [[ "$DRY_RUN" == true ]]; then
    dry_run_summary
    exit 0
  fi

  check_cgroups
  write_k3s_config
  run_installer
  wait_for_ready
  verify_labels
  print_summary
}

main
